### ISSUE TITLE
Consolidate Combined Fishing Lists into a single directory

### ISSUE THREAD

**Issue by bitsofbits** [GlobalFishingWatch/vessel-lists#21]
- [x]  Move combined fishing lists to a single directory.

- [x] Document how they were created.
        - Much of this can probably be taken from current top-level readme.

**Comment by Bjorn-skytruth** [comment]
I have added a description without going into extensive detail because combined fishing lists here should be standardized and replaced as we:

1. apply the more restrictive 1000 position threshold for likely fishing vessels
2. update earlier fishing lists with the better matching methods applied for 2015
3. increase the number of registry sources

Further details can be found in these tickets:
https://github.com/SkyTruth/GFW-Tasks/issues/174
https://github.com/SkyTruth/Benthos/issues/370
